services:
  db:
    build:
      context: ./db
    container_name: app_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apppassword}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    volumes:
      - db_data:/var/lib/postgresql
      - ./backend/app:/app                # Mount the full frontend directory

    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser} -d ${POSTGRES_DB:-appdb}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: app_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-appuser}:${POSTGRES_PASSWORD:-apppassword}@db:5432/${POSTGRES_DB:-appdb}
      APP_ENV: ${APP_ENV:-development}
    volumes:
      - ./backend/app:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db_network
      - web_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
    container_name: app_frontend
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api}
    volumes:
      - ./frontend/app:/app               # Mount the full frontend directory
      - /app/node_modules              # Protect container node_modules from being overwritten
    #ports:
    #  - "5173:5173"                    # Expose Vite's port if you want direct access from the host browser
    depends_on:
      - backend
    networks:
      - web_network
    healthcheck:
          test: ["CMD-SHELL", "nc -z localhost 5173 || exit 1"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 30s
  server:
    build:
      context: ./server
    container_name: app_server
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
      - "${HTTPS_PORT:-443}:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      frontend:
          condition: service_healthy
      backend:
          condition: service_healthy
    networks:
      - web_network

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge
